import { Member } from "@src/app/types";

export const members: Member[] = [
  {
    id: "yoichiro",
    name: "Yoichiro",
    role: "Backend dev",
    bio: "転職活動中",
    avatarSrc: "/avatars/yoichiro.jpg",
    sources: ["https://qiita.com/TechYoichiro/feed.atom"],
    twitterUsername: "TechYoichiro",
    githubUsername: "techyoichiro",
    websiteUrl: "",
  },
  {
    id: "takarada",
    name: "Takarada",
    role: "Chief",
    bio: "CyberAgentのエンジニアコミュニティスペース「CA Tech Lounge」の室長と新卒エンジニア職採用マネージャーを担当しています。AtCoder茶 富山県立山町出身",
    avatarSrc: "/avatars/takarada.jpg",
    sources: [],
    twitterUsername: "y_takarada",
    websiteUrl: "https://www.cyberagent.co.jp/careers/special/students/tech_lounge/",
  },
  {
    id: "newt",
    name: "newt",
    role: "Frontend dev",
    bio: "SIT CY B1 / Web, UX / SecHack365'24 / CA Tech Lounge / FE / #ScoreWatcher の開発 / Discord → http://discord.gg/rct5sx6rbZ",
    avatarSrc: "/avatars/newt.jpg",
    sources: [
      "https://qiita.com/newt239/feed.atom",
      "https://newt239.hatenablog.com/feed",
      "https://zenn.dev/newt_st21/feed"
    ],
    twitterUsername: "newt239",
    websiteUrl: "https://newt239.dev/",
    githubUsername: "newt239",
  },
  {
    id: "fujiken",
    name: "FUJIKEN",
    role: "iOS dev",
    bio: "都内大学4年生。#CATechLounge のiOSエンジニアです。",
    avatarSrc: "/avatars/fujiken.jpg",
    sources: ["https://qiita.com/FJ2123/feed.atom"],
    twitterUsername: "Jiken0705",
    websiteUrl: "https://t.co/Sa2B4bxzSk",
  },
  {
    id: "suu",
    name: "Suu",
    role: "Backend dev",
    bio: "27卒文系エンジニア学生👩‍🎓 🧇waffle college 1期生 | Women go college | TG2024 internship | CA Tech Lounge会員 | #STECH",
    avatarSrc: "/avatars/sumire.jpg",
    sources: ["https://zenn.dev/mire0726/feed"],
    twitterUsername: "Suu_mire0726",
    githubUsername: "mire0726",
  },
  {
    id: "koshimu",
    name: "こここしむ",
    role: "Backend dev",
    bio: "こしむです‼️",
    avatarSrc: "/avatars/koshimu.jpg",
    sources: ["https://note.com/55koshimu/rss"],
    twitterUsername: "55koshimu",
  },
  {
    id: "MxShun",
    name: "しゅん",
    role: "Backend dev",
    bio: "サイバーエージェントで「極予測やりとりAI」というプロダクトの 開発責任者 / EM / スクラムマスター / バックエンドエンジニア をしています",
    avatarSrc: "/avatars/mxshun.jpg",
    sources: [
        "https://qiita.com/mxshun/feed.atom",
        "https://developers.cyberagent.co.jp/blog/archives/author/mxshun/feed",
    ],
    twitterUsername: "MxShun",
    githubUsername: "MxShun",
    websiteUrl: "https://mxshun.github.io",
  },
  {
    id: "OmojiP",
    name: "OmojiP",
    role: "Game Client dev",
    bio: "Unityやってます",
    avatarSrc: "/avatars/omojip.jpg",
    sources: [
        "https://qiita.com/OmojiP/feed.atom",
    ],
    twitterUsername: "OmojiP",
    websiteUrl: "https://unityroom.com/users/omojip",
  },
];
