import { Member } from "@src/app/types";

export const members: Member[] = [
  {
    id: "yoichiro",
    name: "Yoichiro",
    role: "Backend dev",
    bio: "転職活動中",
    avatarSrc: "/avatars/yoichiro.jpg",
    sources: ["https://qiita.com/TechYoichiro/feed.atom"],
    twitterUsername: "TechYoichiro",
    githubUsername: "techyoichiro",
    websiteUrl: "",
  },
  {
    id: "takarada",
    name: "Takarada",
    role: "Chief",
    bio: "気になることは何でも相談して下さい！",
    avatarSrc: "/avatars/takarada.jpg",
    sources: ["https://note.com/hashtag/Atcoder/rss"],
    excludeUrlRegex: "https://www.cyberagent.co.jp/careers/special/students/tech_lounge/",
    twitterUsername: "y_takarada",
    websiteUrl: "https://www.cyberagent.co.jp/careers/special/students/tech_lounge/",
  },
  {
    id: "amanda",
    name: "Amanda",
    role: "Frontend dev",
    bio: "Frontend developer,",
    avatarSrc: "/avatars/amanda.jpg",
    sources: ["https://qiita.com/catnose99/feed.atom"],
    includeUrlRegex: "medium.com|zenn.dev",
    twitterUsername: "catnose99",
  },
  {
    id: "takada_junji",
    name: "Takada Junji",
    role: "Designer",
    bio: "Designing all of the apps in Foo company.",
    avatarSrc: "/avatars/junji.jpg",
    sources: [],
  },
  {
    id: "ota_naoko",
    name: "太田 直子",
    role: "Researcher",
    bio: "Some texts here",
    avatarSrc: "/avatars/naoko.jpg",
    sources: [
      "https://zenn.dev/catnose99/feed",
      "https://catnose.medium.com/feed",
    ],
    includeUrlRegex: "medium.com|zenn.dev",
    twitterUsername: "catnose99",
    githubUsername: "catnose99",
    websiteUrl: "https://catnose99.com",
  },
  {
    id: "alexandria",
    name: "Alexandria",
    role: "Tech Lead",
    bio: "IT professional with 3 years of experience",
    avatarSrc: "/avatars/alexandria.jpg",
    sources: [],
  },
];
